#!/usr/bin/env python3
"""Generate the MOCK sample data used by the demo UI when data/ is missing.

Stdlib only and fully deterministic: running it twice writes identical files.
Everything written here carries backend "mock". None of it is model output,
none of the poles are real, and the pictures are drawn illustrations.

    python demo/sample/make_sample.py
"""

import json
import math
import random
from pathlib import Path

OUT = Path(__file__).resolve().parent
PHOTOS = OUT / "photos"
CENTRE = (-27.56, 151.95)
N_POLES = 56
N_INSPECTED = 40
N_WITH_FILE = 28  # inspected poles beyond this get a photo path with no file (placeholder test)
THRESHOLD = 0.6
RECORDED_AT = "2026-10-08T00:00:00Z"
NOW = 2026
ATTRIBUTION = [
    "Pole photos: PD-Defect, APEPDCL, CC BY 4.0 (not included in this sample)",
    "Pole positions: (c) OpenStreetMap contributors, ODbL (sample positions are synthetic)",
    "Inspection histories: western red cedar pole datasets, utilityanalytics on Kaggle (sample histories are synthetic)",
    "Sample files: generated by demo/sample/make_sample.py, mock data only",
]
HEALTH_LEGEND = {
    "0": "critical: imminent failure risk",
    "1": "poor: significant defects",
    "2": "fair: some defects",
    "3": "good: minor wear",
    "4": "as new",
}
ACTIONS = ["replace", "maintain", "defer", "reinspect"]
CRIT_TYPES = ["hospital", "aged care facility", "water pumping station"]


def r2(x, n=2):
    return round(float(x), n)


def norm(v):
    s = sum(v)
    return [x / s for x in v]


def softmax(logits, temp=1.0):
    m = max(logits)
    e = [math.exp((x - m) / temp) for x in logits]
    return norm(e)


def choice_answer(options, probs):
    probs = norm(probs)
    i = max(range(len(options)), key=lambda k: probs[k])
    return {
        "type": "choice",
        "choice": options[i],
        "probabilities": {o: r2(p, 4) for o, p in zip(options, probs)},
        "confidence": r2(probs[i], 4),
    }


def score_answer(level, rnd, spread):
    centre = level + rnd.uniform(-0.35, 0.35)
    probs = norm([math.exp(-((k - centre) ** 2) / (2 * spread**2)) for k in range(5)])
    mean = sum(k * p for k, p in enumerate(probs))
    return {
        "type": "score",
        "score": r2(mean, 3),
        "probabilities": {str(k): r2(p, 4) for k, p in enumerate(probs)},
        "legend": HEALTH_LEGEND,
        "confidence": r2(max(probs), 4),
    }


def street_positions(rnd):
    """Five 'streets' of poles with jitter, plus the odd stray."""
    pts = []
    per = [12, 12, 11, 11, 10]
    for n in per:
        a = (CENTRE[0] + rnd.uniform(-0.035, 0.035), CENTRE[1] + rnd.uniform(-0.05, 0.05))
        b = (CENTRE[0] + rnd.uniform(-0.035, 0.035), CENTRE[1] + rnd.uniform(-0.05, 0.05))
        for k in range(n):
            t = (k + rnd.uniform(-0.2, 0.2)) / max(n - 1, 1)
            pts.append(
                (
                    a[0] + (b[0] - a[0]) * t + rnd.uniform(-0.0012, 0.0012),
                    a[1] + (b[1] - a[1]) * t + rnd.uniform(-0.0012, 0.0012),
                )
            )
    return pts[:N_POLES]


def make_record(rnd, age, decay, hid):
    """Three inspections 2006/2016/2026 with shell thickness falling at `decay` per decade."""
    t0 = rnd.uniform(0.82, 0.98)
    insps = []
    prev_mean = None
    for k, year in enumerate((2006, 2016, 2026)):
        base = t0 * (1 - decay) ** k
        vals = [r2(max(0.12, base + rnd.uniform(-0.04, 0.04))) for _ in range(3)]
        mean = sum(vals) / 3
        entry = {
            "year": year,
            "shell_thickness": vals,
            "groundline": r2(max(0.1, 0.7 * mean + rnd.uniform(-0.05, 0.05))),
            "surface": "No Defects" if mean > 0.7 else ("Minor Defects" if mean > 0.45 else "Serious Defects"),
            "woodpecker_holes": rnd.random() < (0.05 + 0.5 * decay),
        }
        insps.append(entry)
        prev_mean = mean
    insps[-1]["health_index"] = hid
    first, last = (sum(insps[1]["shell_thickness"]) / 3), (sum(insps[2]["shell_thickness"]) / 3)
    return insps, r2((last - first) / first)


def build_record(rnd, age, decay, hid, bush, customers, crit, ctype, last_maint, source):
    insps, change = make_record(rnd, age, decay, hid)
    return {
        "material": "timber",
        "age_years": age,
        "install_year": NOW - age,
        "inspections": insps,
        "shell_thickness_change_10y": change,
        "transformer": rnd.choice(["none", "none", "single_phase", "three_phase"]),
        "last_maintained_year": last_maint,
        "years_since_maintenance": (NOW - last_maint) if last_maint else None,
        "bushfire_zone": bush,
        "customers_served": customers,
        "critical_customer": crit,
        "critical_customer_type": ctype,
        "source_history_id": source,
    }


def decide(rnd, rec, lean_lat, arm_lat, veg_lat, level, force_uncertain=False):
    """Return a decisions-entry-like dict (mock)."""
    spread = rnd.uniform(0.55, 0.9)

    def peaked(options, idx, sharp):
        logit = [(2.6 * sharp if k == idx else rnd.uniform(0, 0.8)) for k in range(len(options))]
        return softmax(logit)

    lean_opts = ["straight", "leaning", "cannot_assess"]
    arm_opts = ["straight", "tilted", "not_visible"]
    veg_opts = ["clear", "encroaching", "not_visible"]
    sharp = rnd.uniform(0.6, 1.1)
    lean = choice_answer(lean_opts, peaked(lean_opts, lean_lat, sharp))
    arm = choice_answer(arm_opts, peaked(arm_opts, arm_lat, sharp))
    veg = choice_answer(veg_opts, peaked(veg_opts, veg_lat, sharp))
    health = score_answer(level, rnd, spread)
    ms1 = r2(rnd.uniform(34, 62), 1)
    v1 = {
        "answers": {"lean": lean, "crossarm": arm, "vegetation": veg, "health": health},
        "latency_ms": r2(ms1 + rnd.uniform(6, 22), 1),
        "model_ms": ms1,
    }

    # action logits: a stand-in for a policy, mock only
    shell = -rec["shell_thickness_change_10y"]
    risk = 0.9 * (4 - health["score"]) / 4 + 1.4 * shell + (0.25 if lean["choice"] == "leaning" else 0)
    risk += 0.2 if arm["choice"] == "tilted" else 0
    bush = {"high": 0.35, "medium": 0.15, "low": 0}[rec["bushfire_zone"]]
    crit = 0.3 if rec["critical_customer"] else 0
    since = rec["years_since_maintenance"]
    stale = 0.1 if since is None or since > 10 else 0
    s = risk + bush + crit + stale
    # centre of each action on the risk scale s: defer low, maintain middle, replace high
    centres = [1.45, 0.95, 0.45, None]
    logits = [-abs(min(s, 1.6) - c) * 6.0 + 2.2 if c is not None else rnd.uniform(-0.6, 0.2) for c in centres]
    if force_uncertain:
        logits = [x * 0.2 for x in logits]
    probs = softmax(logits, temp=rnd.uniform(0.8, 1.2))
    action = choice_answer(ACTIONS, probs)
    safety = r2(min(0.97, max(0.03, 0.12 + 0.75 * s * 0.8 + rnd.uniform(-0.06, 0.06))), 4)
    ms2 = r2(rnd.uniform(30, 58), 1)
    v2 = {
        "answers": {"action": action, "safety_risk_now": {"type": "noul", "noul": safety}},
        "latency_ms": r2(ms2 + rnd.uniform(6, 20), 1),
        "model_ms": ms2,
    }
    conf = action["confidence"]
    route = "engineer" if (conf < THRESHOLD or lean["choice"] == "cannot_assess") else "auto"
    return {"v1": v1, "v2": v2, "action": action["choice"], "confidence": conf, "route": route}


def pole_svg(lean_lat, arm_lat, veg_lat, level, seed):
    """A schematic ground-level pole drawing. Clearly an illustration, not a photo."""
    rnd = random.Random(seed)
    lean_deg = {0: rnd.uniform(-1.5, 1.5), 1: rnd.choice([-1, 1]) * rnd.uniform(7, 14), 2: 0}[lean_lat]
    arm_deg = {0: rnd.uniform(-1, 1), 1: rnd.choice([-1, 1]) * rnd.uniform(6, 12), 2: 0}[arm_lat]
    wood = ["#4a3a2c", "#5b4636", "#6b5642", "#7a664f", "#8a7760"][level]
    veg = ""
    if veg_lat == 1:
        veg = (
            '<g fill="#3d7a3a" opacity=".9"><circle cx="150" cy="70" r="30"/><circle cx="178" cy="86" r="26"/>'
            '<circle cx="122" cy="86" r="24"/></g>'
        )
    arm = (
        ""
        if arm_lat == 2
        else (
            f'<g transform="rotate({arm_deg:.1f} 160 74)"><rect x="104" y="68" width="112" height="9" rx="2" fill="{wood}"/>'
            '<circle cx="114" cy="68" r="4" fill="#d8dde2"/><circle cx="160" cy="68" r="4" fill="#d8dde2"/>'
            '<circle cx="206" cy="68" r="4" fill="#d8dde2"/></g>'
        )
    )
    cracks = "".join(
        f'<line x1="{156 + rnd.randint(-3, 3)}" y1="{y}" x2="{164 + rnd.randint(-3, 3)}" y2="{y + 14}" '
        'stroke="#1c140d" stroke-width="1.2" opacity=".6"/>'
        for y in range(100, 100 + 40 * (4 - level) // 2, 22)
    )
    return (
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 240" role="img" aria-label="Sample pole illustration">'
        '<defs><linearGradient id="s" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#b9c9d6"/>'
        '<stop offset="1" stop-color="#e6ecf0"/></linearGradient></defs>'
        '<rect width="320" height="240" fill="url(#s)"/><rect y="204" width="320" height="36" fill="#8d9a73"/>'
        f"{veg}{arm}"
        f'<g transform="rotate({lean_deg:.1f} 160 206)"><rect x="153" y="60" width="14" height="148" rx="3" fill="{wood}"/>{cracks}</g>'
        '<line x1="0" y1="72" x2="104" y2="76" stroke="#2b2f33" stroke-width="1.2"/>'
        '<line x1="216" y1="76" x2="320" y2="72" stroke="#2b2f33" stroke-width="1.2"/>'
        '<text x="10" y="230" font-family="sans-serif" font-size="10" fill="#fff" opacity=".9">Sample illustration, not a field photo</text>'
        "</svg>\n"
    )


def main():
    rnd = random.Random(20261008)
    PHOTOS.mkdir(exist_ok=True)
    positions = street_positions(rnd)
    ids = []
    seen = set()
    while len(ids) < len(positions):
        v = rnd.randint(100000, 999999)
        if v not in seen:
            seen.add(v)
            ids.append(f"osm-{v}")
    order = sorted(range(len(positions)), key=lambda i: ids[i])  # stable sort by id like the real register
    positions = [positions[i] for i in order]
    ids = [ids[i] for i in order]
    inspected_idx = set(rnd.sample(range(N_POLES), N_INSPECTED))

    poles, decisions = [], {}
    label_of = {
        "lean": ["Straight", "Leaned", "Rejected"],
        "arm": ["Straight", "Tilted", "Hidden"],
        "veg": ["Safe", "Risky", "Hidden"],
    }
    k_insp = 0
    for i, (lat, lon) in enumerate(positions):
        edge = max(abs(lat - CENTRE[0]) / 0.035, abs(lon - CENTRE[1]) / 0.05)
        rb = rnd.random() - 0.15 * edge
        bush = "high" if rb < 0.0 else "medium" if rb < 0.3 else "low"
        age = rnd.randint(20, 70)
        decay = min(0.45, max(0.03, (age - 15) / 160 + rnd.uniform(-0.04, 0.06)))
        level = max(0, min(4, int(round(4 - (decay / 0.4) * 4 + rnd.uniform(-0.7, 0.7)))))
        hid = {0: 1, 1: 2, 2: 3, 3: 4, 4: 5}[level]
        crit = rnd.random() < 0.08
        last_maint = (
            rnd.choice([None, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025]) if rnd.random() < 0.8 else None
        )
        rec = build_record(
            rnd,
            age,
            decay,
            hid,
            bush,
            int(min(400, 1 + rnd.paretovariate(1.3) * 8)),
            crit,
            rnd.choice(CRIT_TYPES) if crit else None,
            last_maint,
            f"sample-{i + 1}",
        )
        pole = {"id": ids[i], "lat": r2(lat, 6), "lon": r2(lon, 6), "inspected": i in inspected_idx}
        if pole["inspected"]:
            lean_lat = 1 if (decay > 0.28 and rnd.random() < 0.6) or rnd.random() < 0.12 else 0
            if k_insp in (7, 19):
                lean_lat = 2
            arm_lat = 1 if rnd.random() < 0.25 + decay else (2 if rnd.random() < 0.05 else 0)
            veg_lat = 1 if rnd.random() < 0.3 else (2 if rnd.random() < 0.05 else 0)
            if k_insp < N_WITH_FILE:
                fname = f"photos/sample_{k_insp:02d}.svg"
                (OUT / fname).write_text(pole_svg(lean_lat, arm_lat, veg_lat, level, 1000 + k_insp), encoding="utf-8")
            else:
                fname = f"photos/sample_{k_insp:02d}.jpg"  # deliberately absent: UI shows a placeholder
            pole["photo"] = fname
            pole["photo_source"] = {
                "dataset": "sample",
                "label": label_of["lean"][lean_lat],
                "credit": "Sample illustration (mock data), not a field photo",
            }
            decisions[ids[i]] = decide(rnd, rec, lean_lat, arm_lat, veg_lat, level, force_uncertain=(k_insp % 9 == 4))
            k_insp += 1
        pole["record"] = rec
        poles.append(pole)

    # decisions keep a fixed recorded order: the order of poles in the register
    rec_order = [p["id"] for p in poles if p["inspected"]]
    decisions = {k: decisions[k] for k in rec_order}
    write(
        OUT / "poles.json",
        {"generated_at": RECORDED_AT, "town": "Toowoomba, QLD", "attribution": ATTRIBUTION, "poles": poles},
    )
    write(
        OUT / "decisions.json",
        {
            "backend": "mock",
            "model": "matilda-jev-v1",
            "hardware": "none (mock backend)",
            "recorded_at": RECORDED_AT,
            "engineer_threshold": THRESHOLD,
            "decisions": decisions,
        },
    )

    # flip: one photo, two contrasting records
    frnd = random.Random(77)
    young = build_record(frnd, 23, 0.04, 4, "low", 38, False, None, 2024, "sample-flip-a")
    old = build_record(frnd, 66, 0.34, 1, "high", 260, True, "aged care facility", None, "sample-flip-b")
    old["inspections"][2]["surface"] = "Serious Defects"
    young["inspections"][2]["surface"] = "No Defects"
    sides = []
    for label, rec, force in (
        ("Younger pole, low bushfire zone, maintained 2 years ago", young, "defer"),
        ("Older pole, high bushfire zone, aged care customer", old, "replace"),
    ):
        lvl = 3 if rec is young else 1
        for attempt in range(2000):
            d = decide(random.Random(900 + attempt + (0 if rec is young else 500)), rec, 1, 0, 0, lvl)
            if d["action"] == force and d["route"] == "auto":
                break
        sides.append({"label": label, "record": rec, **d})
    (OUT / "photos" / "sample_flip.svg").write_text(pole_svg(1, 0, 1, 2, 4242), encoding="utf-8")
    write(
        OUT / "flip.json",
        {
            "backend": "mock",
            "model": "matilda-jev-v1",
            "recorded_at": RECORDED_AT,
            "photo": "photos/sample_flip.svg",
            "photo_source": {
                "dataset": "sample",
                "label": "Leaned",
                "credit": "Sample illustration (mock data), not a field photo",
            },
            "sides": sides,
        },
    )

    # eval summary (mock): plausible shapes, not a measurement
    erand = random.Random(5)
    tasks = {}
    spec = {
        "lean": (["straight", "leaning", "cannot_assess"], 120, 0.86),
        "crossarm": (["straight", "tilted", "not_visible"], 90, 0.81),
        "vegetation": (["clear", "encroaching", "not_visible"], 100, 0.78),
        "record_health_index": (["1", "2", "3", "4", "5"], 150, 0.62),
    }
    for name, (labels, n, acc) in spec.items():
        tasks[name] = eval_task(erand, labels, n, acc)
    write(
        OUT / "eval_summary.json",
        {
            "backend": "mock",
            "model": "matilda-jev-v1",
            "hardware": "none (mock backend)",
            "recorded_at": RECORDED_AT,
            "tasks": tasks,
        },
    )
    print(f"wrote sample: {len(poles)} poles, {len(decisions)} decisions")


def eval_task(rnd, labels, n, acc):
    k = len(labels)
    weights = [1.0 + rnd.random() for _ in labels]
    counts = [max(3, int(n * w / sum(weights))) for w in weights]
    confusion = {a: {b: 0 for b in labels} for a in labels}
    bins = [{"n": 0, "conf": 0.0, "hit": 0} for _ in range(10)]
    correct = 0
    total = 0
    for i, a in enumerate(labels):
        for _ in range(counts[i]):
            conf = min(0.99, max(1 / k, rnd.betavariate(5, 2) * 0.9 + 0.1 * (1 / k)))
            hit = rnd.random() < min(0.98, max(0.1, acc + (conf - 0.75) * 0.5))
            pred = a if hit else rnd.choice([b for b in labels if b != a])
            confusion[a][pred] += 1
            b = min(9, int(conf * 10))
            bins[b]["n"] += 1
            bins[b]["conf"] += conf
            bins[b]["hit"] += 1 if hit else 0
            correct += hit
            total += 1
    f1s = []
    for a in labels:
        tp = confusion[a][a]
        fp = sum(confusion[b][a] for b in labels if b != a)
        fn = sum(confusion[a][b] for b in labels if b != a)
        f1s.append(2 * tp / (2 * tp + fp + fn) if tp else 0.0)
    rel = [
        {
            "bin": f"{i / 10:.1f}-{(i + 1) / 10:.1f}",
            "mean_confidence": r2(b["conf"] / b["n"], 4),
            "accuracy": r2(b["hit"] / b["n"], 4),
            "count": b["n"],
        }
        for i, b in enumerate(bins)
        if b["n"]
    ]
    ece = sum(abs(x["mean_confidence"] - x["accuracy"]) * x["count"] for x in rel) / total

    def pct(base):
        return {"p50": r2(base, 1), "p90": r2(base * 1.3, 1), "p99": r2(base * 1.8, 1)}

    base = rnd.uniform(38, 55)
    return {
        "n": total,
        "accuracy": r2(correct / total, 4),
        "macro_f1": r2(sum(f1s) / k, 4),
        "confusion": confusion,
        "ece": r2(ece, 4),
        "reliability": rel,
        "latency_ms": pct(base + 14),
        "model_ms": pct(base),
        "backend": "mock",
        "hardware": "none (mock backend)",
        "recorded_at": RECORDED_AT,
    }


def write(path, obj):
    path.write_text(json.dumps(obj, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
